- src/App.tsx
- tsconfig.node.json
- vite.config.ts
- Closes #3 
1. emotion css 초기세팅
- vite.config.ts, tsconfig.node.json 파일 수정
- emotion css 적용 결과 이상 없었습니다.
> [Setting/#3] emotion css 초기설정 세팅

- tsconfig.app.json
- Closes #6
1. tsconfig.app.json 수정
- "jsxImportSource": "@emotion/react" 추가
- @emotion/react 설정 중 누락된 설정 추가
tsconfig.app.json 에 위 설정 추가해주면, 별도의 Import 없이 css`` 사용 가능
> fix: jsxImportSource 설정 수정

- index.html
- src/styles/global.ts
- src/styles/theme.ts
- Closes #17 
1. 폰트 설정
- Pretendard 폰트 설정
- 분명 폰트설정을 해줬던 것 같은데,,, 왜 빼먹어졌는지 모르겠네요
- 신경쓰지말고 그냥 하던 것 처럼 Font불러와서 쓰면 됩니다.
> [Setting/#17] 프로젝트 폰트 설정

- README.md
- Closes #32
1. 리드미 수정
- 임화랑 장정안 사진 바껴있음
- ㅋㅋㅋ 죄송요,,
> [Docs/#32] 리드미 팀원 사진 수정

- src/components/common/buttons/Button/Button.style.ts
- src/components/common/buttons/Button/Button.tsx
- src/components/common/buttons/PayButton/PayButton.style.ts
- src/pages/dev/page/Components/Components.tsx
- Closes #94 
1. PayButton, Button 컴포넌트 스타일 수정
- PayButton은 width값이 고정이기 때문에 rem으로 수정
- Button컴포넌트는 size대신 variant 값을 prop으로 받고, large, medium, small, xSmall, stroke, round 값에 따라 다른 스타일 가집니다.
-
> [Refactor/#94] button refactor

- src/components/common/ImageSelect/ImageSelect.style.ts
- src/components/common/TextArea/TextArea.tsx
- src/pages/class/page/ClassNotice/ClassNotice.style.ts
- src/pages/class/page/ClassNotice/ClassNotice.tsx
- Closes #121
1. 공지사항 작성하기 페이지 퍼블리싱
- 컴포넌트 잘 조립했습니다.
- 헤더 정안이형이 수정해서, 그거 머지하면 헤더색도 흰색으로 바뀔 예정입니다.
- 사진도 업로드까지는 되는데 presigned url 연동하면서 좀 더 수정할 예정입니다.
> [Feat/#121] 공지사항 작성하기 페이지

- src/components/common/Footer/Footer.style.ts
- src/components/common/Footer/Footer.tsx
- src/constants/category.tsx
- src/pages/home/page/Home/Home.style.ts
- src/pages/home/page/Home/Home.tsx
- Closes #1
1. 내용
- home UI 구현
- 단순 뷰 구현이라 따로 고민사항은 없었습니다
> [Feat/#133] home UI 구현 (footer 위치 스타일코드 아직 보류)

- src/components/common/buttons/Button/Button.style.ts
- src/components/common/buttons/Button/Button.tsx
- src/pages/dev/page/Components/Components.tsx
- src/pages/myPage/components/LogoutModal/LogoutModal.style.ts
- src/pages/myPage/components/LogoutModal/LogoutModal.tsx
- Closes #180 
1. 로그아웃시 뜨는 모달 컴포넌트 완성
- 기존의 Modal컴포넌트에 호출할 내부 컨텐츠 모달을 생성했습니다.
-
> [Feat/#180] logout 모달 완성

- src/apis/domains/presignedUrl/index.ts
- src/assets/svg/IcCaution.tsx
- src/pages/class/page/ClassApply/ClassApplyQuestion/ClassApplyQuestion.tsx
- src/pages/class/page/ClassNotice/ClassNotice.tsx
- src/pages/dev/page/Components/Components.tsx
- src/pages/host/components/HostMyClassCard/HostMyClassCard.tsx
- Closes #193
1. 오류 수정
- import 경로 문제로 배포환경에서 실행이 안돼서 해당 오류 수정했습니다.
- 수정하는 과정에서 몇몇오류 더 보여서 수정했습니다.
- 배포할때 yarn build를 해야하는데 이 과정에서 빨간줄 하나라도 모두 에러로 잡혀서, 다들 yarn build해보고 뜨는 오류도 다 수정해야할 것 같습니다.
- 대부분 type, mock data, dev페이지 에서 발생하는 오류라서 현재 올라온 PR들 모두 머지되면 대부분 해결될 것으로 보임
> [Deploy/#193] 배포 오류 수정

- src/apis/domains/host/useFetchMoimHost.ts
- src/apis/domains/moim/useFetchGuestApply.ts
- src/apis/domains/moim/useFetchHostMoimInfo.ts
- src/apis/domains/moim/useFetchQuestionList.ts
- src/apis/domains/notice/useFetchMoimNoticeList.ts
- src/constants/mocks/HostMyClassCardData.ts
- src/pages/class/page/ClassApply/ClassApplyQuestion/ClassApplyQuestion.tsx
- src/pages/guest/components/MoimCard/MoimCard.tsx
- src/pages/host/components/HostMyClassCard/HostMyClassCard.tsx
- src/types/api/schema/index.ts
- src/types/responseType.ts
- Closes #185 
1. responseType.ts에 있는 타입이 사용되는 모든 파일 스키마 타입으로 수정
-
> [Feat/#185] responseType.ts에 사용되는 모든 타입 스키마로 수정

- index.html
- src/pages/categories/page/Categories/Categories.style.ts
- src/pages/categories/page/Categories/Categories.tsx
- src/pages/class/page/ClassApply/ClassApplyComplete/ClassApplyComplete.tsx
- Closes #198 
1. 내용
- og태그 추가하였습니다
-
> [Feat/#198] og tag 추가 (썸네일 및 description은 추후 기획에서 전달 받고 수정)

- src/apis/domains/moim/usePostMoim.ts
- src/components/common/ImageSelect/ImageSelect.tsx
- src/components/common/buttons/SelectButton/SelectButton.tsx
- src/components/common/inputs/AccountNumberInput/AccountNumberInput.tsx
- src/pages/class/components/StepFour/StepFour.tsx
- src/pages/class/components/StepOne/StepOne.tsx
- src/pages/class/components/StepThree/StepThree.tsx
- src/pages/class/hooks/useClassPostInputChange.ts
- src/pages/class/hooks/useClassPostInputValidation.ts
- src/pages/class/page/Class/Class.tsx
- src/pages/class/page/ClassApply/ClassApplyQuestion/ClassApplyQuestion.tsx
- src/pages/class/page/ClassNotice/ClassNotice.tsx
- src/pages/dev/page/Components/Components.tsx
- src/pages/myPage/components/HostInfoCardWithLink/HostInfoCardWithLink.style.ts
- src/pages/myPage/components/HostInfoCardWithLink/HostInfoCardWithLink.tsx
- src/stores/classPostData.ts
- Closes #205 
1. 각종 기능 QA 수정 및 반영했습니다.
- 호스트 마이페이지에서 프로필 링크 클릭시 그 링크로 라우팅 (_blank)
- 계좌번호만 입력할 수 있는(숫자만 입력) AccountNumberInput 컴포넌트 구현 및 필요한 부분에 삽입
- 모임개설 성공 후 개설한 모임 보러가기 버튼 클릭시 모임 상세 페이지로 이동
- 이미지 개수에 맞게 캐러셀 생성
- 모임 개설시 이미지 추가하는것과 관련된 에러 모두 수정
- class/post/step3의 validation 수정
- 게스트는 공지사항 적을 수 없도록 수정
- 내가 개설한 모임에 참여하기 버튼 비활성화
-
> [Fix/#205] 기능QA 반영

- src/components/common/Toast/Toast.style.ts
- src/components/common/buttons/InterestCategoryButton/InterestCategoryButton.style.ts
- src/pages/class/page/ClassApply/ClassApplyDeposit/ClassApplyDeposit.style.ts
- src/pages/host/page/MyClassManage/MyClassManage.style.ts
- src/pages/host/page/MyClassManage/MyClassManage.tsx
- src/pages/myPage/components/HostInfoCardWithLink/HostInfoCardWithLink.tsx
- Closes #211
1. Toast
데스크탑으로 봤을 때 크기가 작게 나오는 토스트 -> 태승쌤이 미디어 쿼리로 해결
2. errorModalButton
글자보다 border bottom 이 더 길게 나오는 버튼 -> padding 0으로 해결
3. HostInfoCardWithLink
hostLink 없을 때 아무것도 안 뜨도록 수정
interestcategorybutton 이 하나만 나올 경우, 프로필 크기만큼 커짐 -> width 고정으로 해결
-
> [Feat/#211] Toast, errorModalButton, HostInfoCardWithLink 수정

- src/components/common/CountPeople/CountPeople.style.ts
- src/components/common/CountPeople/CountPeople.tsx
- src/components/common/ImageSelect/ImageSelect.style.ts
- src/components/common/ImageSelect/ImageSelect.tsx
- src/components/common/QuestionText/QuestionText.style.ts
- src/components/common/QuestionText/QuestionText.tsx
- src/pages/class/components/AddAmountBox/AddAmountBox.style.ts
- src/pages/class/components/StepOne/StepOne.style.ts
- src/pages/class/components/StepOne/StepOne.tsx
- src/pages/class/components/StepThree/StepThree.tsx
- src/pages/class/components/StepTwo/StepTwo.tsx
- src/pages/class/page/Class/Class.tsx
- src/pages/class/page/ClassNotice/ClassNotice.tsx
- src/pages/dev/page/Components/Components.tsx
- Closes #212 
1. 각종 에러를 수정했습니다.
- CountPeople, QuestionText 드래그 막기
- AddAmountBox 금액 버튼 커서 포인터 및 사파리에서 깨지는 width 수정
- 사파리 ImageSelect svg아이콘 깨지는거 수정
- 클래스 상세에서 스크롤 제일 아래까지 내리고 참여하기 버튼 클릭했을때 다음 페이지 최상단으로 스크롤
-
> [Fix/#212] fix last error

- README.md
- Closes #220
1. 리꾸
- 리드미 최신화 했습니다.
> [Docs/#220] 로그인 기능 추가

- src/components/common/QuestionText/QuestionText.style.ts
- src/components/common/TextArea/TextArea.style.ts
- src/pages/categories/components/ClassListCard/ClassListCard.style.ts
- src/pages/categories/components/ClassListCard/ClassListCard.tsx
- src/pages/class/page/Class/Class.style.ts
- src/pages/class/page/Class/Class.tsx
- src/pages/class/page/ClassApply/ClassApplyQuestion/ClassApplyQuestion.style.ts
- src/pages/class/page/ClassApply/ClassApplyQuestion/ClassApplyQuestion.tsx
> [Fix/#229] 디자인 QA반영

- index.html
- src/components/common/Label/Label.style.ts
- src/components/common/TimeSelect/TimeSelect.style.ts
- src/components/common/TimeSelect/TimeSelect.tsx
- src/pages/class/components/StepThree/StepThree.tsx
- src/pages/class/page/Class/Class.style.ts
- src/pages/class/page/Class/Class.tsx
- src/pages/guest/page/GuestMyClass/GuestMyClass.style.ts
- src/pages/guest/page/GuestMyClass/GuestMyClass.tsx
- src/pages/host/components/HostMyClassEmptyView/HostMyClassEmptyView.tsx
- src/pages/host/components/StepTwo/StepTwo.tsx
- src/pages/host/page/HostMyClass/HostMyClass.tsx
- Closes #1
1. 내용
- 새벽 5시 기준 qa입니다.
-
> [Fix/#226] 05시 기준 qa

- src/apis/domains/host/useFetchMoimHost.ts
- src/apis/domains/host/usePostHostApply.ts
- src/apis/domains/moim/useFetchGuestApply.ts
- src/apis/domains/moim/useFetchGuestParticipate.ts
- src/apis/domains/moim/useFetchHostMoimInfo.ts
- src/apis/domains/moim/useFetchMoimBanner.ts
- src/apis/domains/moim/useFetchMoimCategories.ts
- src/apis/domains/moim/useFetchMoimDescription.ts
- src/apis/domains/moim/useFetchMoimDetail.ts
- src/apis/domains/moim/useFetchMoimListByCategory.ts
- src/apis/domains/moim/useFetchMyHost.ts
- src/apis/domains/moim/useFetchQuestionList.ts
- src/apis/domains/moim/useFetchSubmittedMoimDetail.ts
- src/apis/domains/moim/usePostMoim.ts
- src/apis/domains/moimSubmission/useFetchSubmitRequest.ts
- src/apis/domains/moimSubmission/useFetchSubmitterList.ts
- src/apis/domains/moimSubmission/usePatchSubmitter.ts
- src/apis/domains/moimSubmission/usePostAnswerList.ts
- src/apis/domains/notice/useFetchMoimNoticeList.ts
- src/apis/domains/notice/usePostNotice.ts
- src/apis/domains/presignedUrl/useFetchPresignedUrl.ts
- src/apis/domains/submitter/useFetchHostSubmitterList.ts
- src/apis/domains/submitter/usePatchHostSubmitter.ts
- src/apis/domains/user/usePostKakaoLogin.ts
- src/apis/domains/user/usePostLogout.ts
- src/types/api/schema/index.ts
- Closes #248
1. API 버전 추가
- 기존 모두 v1이었는데 v2가 추가로생김에 따라서, base url에서 버전을 빼고, api를 호출하는 쪽에서 버전을 추가하도록 수정
- 앞으로 api 연동할때 v1, v2,,, 등등 앞에 붙여서 사용해주셔야 합니다.
- 제가 일괄수정하는 과정에서 잘못 수정된것들 있을 수도 있으니, 작업하실때 오류나도 당황하지마시고 확인한번 해보셔요
- 
이렇게 API 를 호출하는 api/domains/ 안의 파일들에서 endpoint에 /v1, /v2가 추가됐습니다.
이후 스프린트에서 추가/수정되는 API 들에는 v3, v4 이런식으로 붙는다고 하니 항상 붙여서 작업해주시면됩니다!
이 버전을 통해서 어떤 API가 추가/수정되었는지 알 수 있고, 이전 API 로 요청이 가는 등의 문제도 방지할 수 있습니다.
> [Refactor/#248] api 버전 추가

- .github/workflows/ec2Deploy.yaml
- Closes #271
1. Github Actions 배포 자동화
- main 브랜치가 트리거 이구요, main브랜치에 push되면 (우리의 경우 develop -> main 머지 될때) 재배포 되도록 스크립트 작성했습니다. 
- 일단 테스트 했을 땐 되는거 같아보였는데,,, 했는데 안되면 다시 수정해볼게요
Github Actions 잘 실행 됨
nginx 같은 시간에(15분전) 재시작 됨
> [Deploy/#271] 배포 자동화

- src/components/common/inputs/Input/Input.tsx
- src/hooks/useEasyNavigate.ts
- src/pages/class/components/StepTwo/StepTwo.style.ts
- src/pages/host/components/StepOne/StepOne.style.ts
- src/pages/host/components/StepThree/StepThree.tsx
- src/pages/host/components/StepTwo/StepTwo.style.ts
- src/pages/host/components/StepTwo/StepTwo.tsx
- src/pages/host/hooks/useHostApplyInputChange.ts
- src/pages/host/hooks/useHostApplyInputValidation.ts
- src/stores/hostApplyData.ts
- Closes #274 
1. 내용
- 스픽커 신청 폼 작성하는 퍼널구조에서 5번 문항을 기존 카테고리 선택에서 스픽커 소개 키워드 문항으로 수정했습니다.
- 이에 따라 스픽커 신청 폼을 다루는 atom, inputChange, validation, css 등 모두 수정했습니다.
- 최종 스픽커 신청 성공 후 기존 goCategories 에서 goClassList로 수정하였습니다. (useEasyNavigate.ts)
- 이거 머지하고 나서 build에러 마저 해결하면 될 것 같아요.
> [Feat/#274] 스픽커 신청 페이지 수정

- src/apis/domains/review/usePostReview.ts
- src/components/common/Review/Review.style.ts
- src/components/common/Review/Review.tsx
- src/components/common/TextArea/TextArea.style.ts
- src/components/common/index.ts
- src/components/common/inputs/Input/Input.style.ts
- src/components/common/inputs/Input/Input.tsx
- src/pages/class/components/StepOne/StepOne.style.ts
- src/pages/class/components/StepOne/StepOne.tsx
- src/pages/guest/components/DepositModal/DepositModal.style.ts
- src/pages/guest/page/GuestMyClassReviewWrite/GuestMyClassReviewWrite.tsx
- src/pages/host/components/StepOne/StepOne.tsx
- src/pages/host/hooks/useHostApplyInputValidation.ts
- Closes #299 
1. 내용
- 디자인 QA반영
-
> [Fix/#299] 디자인 QA

- index.html
- Closes #305 
---
---
1. 내용1
- GA코드 추가
2. 내용2
- GA코드 추가
---
-
---
> [feat/#305] GA코드 추가

- src/assets/svg/IcOffline.tsx
- Closes #315 
---
---
1. 내용1
- 설명
2. 내용2
- 설명
---
-
---
> [Fix/#315] 필요없는 아이콘 import 제거

- src/pages/class/components/ClassNoticeEmptyView/ClassNoticeEmptyView.tsx
- src/pages/class/components/DeleteNoticeModal/DeleteNoticeModal.tsx
- src/pages/class/components/NoticeCard/NoticeCard.tsx
- src/pages/class/components/StepOne/StepOne.style.ts
- src/pages/class/components/StepOne/StepOne.tsx
- src/pages/class/components/StepThree/StepThree.tsx
- src/pages/class/components/StepTwo/StepTwo.tsx
- src/pages/class/page/Class/Class.tsx
- src/pages/class/page/ClassNotice/ClassNotice.tsx
- src/pages/class/page/ClassNoticeDetail/ClassNoticeDetail.tsx
- src/pages/dev/page/Components/Components.tsx
- src/pages/guest/components/GuestMyClassEmptyView/GuestMyClassEmptyView.style.ts
- src/pages/guest/components/GuestMyClassEmptyView/GuestMyClassEmptyView.tsx
- src/pages/guest/page/GuestMyClass/GuestMyClass.tsx
- src/pages/host/components/StepOne/StepOne.tsx
- src/pages/host/components/StepTwo/StepTwo.tsx
- src/pages/host/hooks/useHostApplyInputValidation.ts
- src/pages/host/page/HostInfoEditPage/HostInfoEditPage.tsx
- src/pages/host/page/MyClassManage/MyClassManage.tsx
- Closes #317 
---
---
1. 내용1
- 설명
2. 내용2
- 설명
---
-
---
> [Fix/#317] THE LAST QA였던 것

- src/pages/admin/components/MoimSubmitter/MoimSubmitter.style.ts
- src/pages/admin/components/MoimSubmitter/MoimSubmitter.tsx
- src/pages/class/components/StepOne/StepOne.style.ts
- src/types/api/schema/index.ts
- Closes #323
---
---
1. 관리자 페이지에 계좌번호 등 관련된 부분 추가했습니당
---
-
---
> [fix/#323] 관리자 페이지에 계좌번호 추가하기

- public/svg/ic_next.svg
- src/assets/svg/IcNext.tsx
- src/components/common/NavigateBox/NavigateBox.style.ts
- src/pages/class/components/HostProfileCard/HostProfileCard.style.ts
- src/pages/myPage/page/GuestMyPage/GuestMyPage.style.ts
- src/pages/myPage/page/HostMyPage/HostMyPage.style.ts
- Closes #321 
---
---
---
-
---
> [Fix/#321] IcNext 아이콘 새로 추출 및 간격 조정

- src/pages/guest/page/GuestMyClassReviewWrite/GuestMyClassReviewWrite.tsx
- Closes #319 
---
---
1. placeholder 텍스트 수정
- 리뷰 작성 페이지 placeholder 텍스트 수정
---
-
---
> [Fix/#319] placeholder 수정

- public/svg/active/ic_all_active.svg
- public/svg/inactive/ic_all_inactive.svg
- src/assets/svg/active/IcAllActive.tsx
- src/assets/svg/active/index.ts
- src/assets/svg/inactive/IcAllInactive.tsx
- src/assets/svg/inactive/index.ts
- src/constants/category.tsx
- src/pages/classList/page/ClassList/ClassList.tsx
- src/pages/home/page/Home/Home.tsx
- Closes #333
---
---
1. 카테고리 '전체' 가 추가되었습니다.
2. 처음 배너 클릭하면 전체 카테고리로 이동합니다.
---
- 파이팅팅!
---
> [Feat/#333] 클래스 리스트에 '전체' 추가

- index.html
- src/apis/api.ts
- src/pages/classList/page/ClassList/ClassList.tsx
- src/pages/myPage/page/HostMyPage/HostMyPage.tsx
- src/types/commonType.ts
- Closes #338 
---
---
1. 인증 로직 수정
2. 카테고리 눌렀을때 스크롤 오류수정
3. 스픽커 마이페이지 새로고침 오류 수정
> [Fix/#338] QA 반영
